// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Mutation struct {
}

type Product struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type Query struct {
}
